basic_settings:
  site_title: Kelsie Gosser's Portfolio
  favicon_image: /images/favicon.svg

header_settings:
  logo_image: /images/logo.svg
  logo_width: 60

menu_settings:
  menu_items:
    - title: 'Portfolio'
      url: '/'
    - title: 'Resume'
      url: '/resume'
    - title: 'About'
      url: '/about'

footer_settings:
  footer_tagline: kelsie.gosser@gmail.com

hero_settings:
  overlay_opacity: 0.7

post_settings:
  grid_spacing: 36

contact_settings:
  form_action: ''
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

social_settings:
  linkedin_url: 'https://www.linkedin.com/in/kelsie-gosser-458254a4/'
  github_url: 'https://github.com/kelsiegosser'
  instagram_url: 'https://www.instagram.com/kelsie.gosser/'
  dribbble_url: 'https://dribbble.com/kelsiegosser'
  facebook_url: ''
  twitter_url: ''
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  behance_url: ''
  deviantart_url: ''
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''

color_settings:
  background_color: '#ffffff' #white
  background_alt_color: '#D1DCE0' #light
  text_dark_color: '#263033' #darkest
  text_medium_color: '#92A3A8' #medium
  text_light_color: '#F2F8FA' #lightest
  accent_color: '#465459' #dark
  border_color: '#F2F8FA' #lightest
  hero_background_color: '#465459' #dark
  hero_text_color: '#ffffff' #white
  error_color: '#D14D23' #red

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css2?family=Heebo:wght@100;200;300;400;500;600;700;800;900&family=Playfair+Display:wght@400;500;600&display=swap" rel="stylesheet">'
  title_font: '"Playfair Display", sans-serif'
  body_font: '"Heebo", sans-serif'
  regular_weight: 500
  bold_weight: 700
  site_title:
    small_size: 25
    medium_size: 30
    large_size: 62
    weight: 700
    letter_spacing: 0
  menu:
    small_size: 30
    medium_size: 16
    large_size: 18
    weight: 500
    letter_spacing: 0.02
  h1:
    small_size: 35
    medium_size: 38
    large_size: 42
    weight: 700
    letter_spacing: 0
    line_height: 1.2
  h2:
    small_size: 22
    medium_size: 30
    large_size: 32
    weight: 500
    letter_spacing: 0
    line_height: 1.2
  h3:
    small_size: 22
    medium_size: 24
    large_size: 26
    weight: 500
    letter_spacing: 0
    line_height: 1.3
  h4:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 500
    letter_spacing: 0
    line_height: 1.4
  h5:
    small_size: 17
    medium_size: 18
    large_size: 18
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 16
    large_size: 16
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 16
    medium_size: 18
    large_size: 20
    weight: 400
    letter_spacing: 0.02
    line_height: 1.6
  blockquote:
    small_size: 25
    medium_size: 30
    large_size: 35
    weight: 300
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 600
    letter_spacing: 0

advanced_settings:
  ajax_loading: true
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""