exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"


repository: kelsiestevenson.github.io
name: Kelsie Stevenson
title: Kelsie's Portfolio
baseurl: ""
markdown: kramdown

sass:
    style: :compressed

collections:
  projects:
    output: true
  contacts:
    output: true

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "contacts"
    values:
      layout: "default"
  - scope:
      path: ""
    values:
      layout: "default"

# github: [metadata]
